export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

export const OPEN_COMMENT_EDITOR = 'OPEN_COMMENT_EDITOR';
export const CLOSE_COMMENT_EDITOR = 'CLOSE_COMMENT_EDITOR';